<footer class="main-footer" id="footer">
  <div class="main-footer__inner">
    <div class="main-footer__company">
      <div class="main-footer__logo">
        <span class="ir">NEXUS GAS</span>
      </div>
      <p class="main-footer__copyright">
        Copyright © 2025 NEXUSGAS. <br />
        All rights reserved.
      </p>
    </div>
    
    <div class="main-footer__info">
      <ul class="main-footer__site">
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">회사소개</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">고객문의</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">투자정보</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">프로젝트</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">사업분야</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">오시는 길</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">채용정보</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">지속가능경영</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">홍보센터</a>
        </li>
        <li class="main-footer__site-item">
          <a href="#" class="main-footer__site-link">NEXUS™ 솔루션</a>
        </li>
      </ul>

      <div class="main-footer__contact-wrap">
        <dl class="main-footer__contact">
          <div class="main-footer__contact-row">
            <div class="main-footer__contact-column">
              <dt>주소</dt>
              <dd>전라남도 광양시 희망길 12-14, 2층 (제철회관)</dd>
            </div>
          </div>
          <div class="main-footer__contact-row">
            <div class="main-footer__contact-column">
              <dt>대표전화</dt>
              <dd>+82-61-795-7495</dd>
            </div>
            <div class="main-footer__contact-column">
              <dt>팩스</dt>
              <dd>+82-61-795-7498</dd>
            </div>
          </div>
          <div class="main-footer__contact-row">
            <div class="main-footer__contact-column">
              <dt>이메일</dt>
              <dd>contact@nexusgas.co.kr</dd>
            </div>
          </div>
        </dl>
        <div class="main-footer__sns">
            <a href="#" class="main-footer__sns-item youtube">
              <span class="ir">youtube</span>
            </a>
            <a href="#" class="main-footer__sns-item instagram">
              <span class="ir">instagram</span>
            </a>
        </div>
      </div>

      <div class="main-footer__policy">
        <a href="#" class="main-footer__policy-link">개인정보 보호정책</a>
        <a href="#" class="main-footer__policy-link">서비스 약관</a>
        <a href="#" class="main-footer__policy-link">쿠키 설정</a>
      </div>
    </div>
  </div>
</footer>
