<!-- HEADER -->
<header class="main-header" id="header">
  <div class="main-header__inner">
    <a href="#" class="main-header__logo">
      <span class="ir">NEXUS</span>
    </a>
    <div class="main-header__gnb gnb">
      <ul class="gnb__list">
        <li class="gnb__item">
          <a href="#" class="gnb__link">NEXUS GAS</a>
        </li>
        <li class="gnb__item">
          <a href="#" class="gnb__link">사업분야</a>
        </li>
        <li class="gnb__item">
          <a href="#" class="gnb__link">제품</a>
        </li>
        <li class="gnb__item">
          <a href="#" class="gnb__link">홍보</a>
        </li>
        <li class="gnb__item">
          <a href="#" class="gnb__link">지속가능성</a>
        </li>
        <li class="gnb__item">
          <a href="#" class="gnb__link">채용</a>
        </li>
      </ul>
    </div>
    <div class="main-header__util">
      <div class="main-header__util-item">
        <button type="button" class="main-header__util-button">고객지원</button>
      </div>

      <div class="main-header__util-item">
        <button type="button" class="main-header__util-button has-dropdown">
          KR
        </button>
      </div>
    </div>
  </div>
</header>
